version: '3.8'
services:
  frontend:
    build:
      context: ./frontend  # This sets the build context to the frontend directory
      dockerfile: Dockerfile  # This references the Dockerfile within the frontend directory
    ports:
      - "80:80"

  backend:
    build:
      context: ./server  # This sets the build context to the server directory
      dockerfile: Dockerfile  # This references the Dockerfile within the server directory
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
