version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_PORT}:80'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:3000'
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    command: ["node", "dist/index.js"]

  db:
    image: postgres:latest
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
